name: Run Fuzzer on push to main

on:
  push:
    branches:
      - main

jobs:
  fuzzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: javac Fuzzer.java 
      - run: java Fuzzer "./html_parser_linux_x86_64"