name: Run Fuzzer on push to main

on:
  push:
    branches:
      - main

jobs:
  fuzzer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - run: echo "Run Fuzzer"
      - run: echo "$PWD"
      - run: ls
      - run: cat *.md
      - run: javac --version
      - run: javac Fuzzer.java 
      - run: java Fuzzer "./html_parser_linux_x86_64"